findbulb_homepage:
    path:     /home
    defaults: { _controller: FindbulbBundle:Findbulb:index }

#paczka idea - jej routing
fosfindbulb_idea:
    resource: "@FindbulbBundle/Resources/config/routing-idea.yml"
    prefix: /idea
    
#user
fosfindbulb_user:
    resource: "@FindbulbBundle/Resources/config/routing-user.yml"
    prefix: /user



    